
ALTER TABLE Student NOCHECK CONSTRAINT ALL

ALTER TABLE SemesterCourse NOCHECK CONSTRAINT ALL  

ALTER TABLE SemesterCoursePrerequisite NOCHECK CONSTRAINT ALL 

ALTER TABLE Course NOCHECK CONSTRAINT ALL  

ALTER TABLE CoursePrerequisite NOCHECK CONSTRAINT ALL  

ALTER TABLE Faculty NOCHECK CONSTRAINT ALL  

ALTER TABLE LuDepartment NOCHECK CONSTRAINT ALL  

ALTER TABLE LuSemester NOCHECK CONSTRAINT ALL  

ALTER TABLE StudentCourse NOCHECK CONSTRAINT ALL

ALTER TABLE Person NOCHECK CONSTRAINT ALL