
ALTER TABLE Student CHECK  CONSTRAINT ALL

ALTER TABLE SemesterCourse CHECK  CONSTRAINT ALL  

ALTER TABLE SemesterCoursePrerequisite CHECK  CONSTRAINT ALL 

ALTER TABLE Course CHECK  CONSTRAINT ALL  

ALTER TABLE CoursePrerequisite CHECK  CONSTRAINT ALL  

ALTER TABLE Faculty CHECK  CONSTRAINT ALL  

ALTER TABLE LuDepartment CHECK  CONSTRAINT ALL  

ALTER TABLE LuSemester CHECK  CONSTRAINT ALL  

ALTER TABLE StudentCourse CHECK  CONSTRAINT ALL

ALTER TABLE Person CHECK  CONSTRAINT ALL